{% set name = "responsefun" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/maxscheurer/responsefun/archive/{{ version }}.tar.gz
  sha256: 8601f3441eef0a5cfc48ae78636cacbdc7385c9a469c02341de175f1f1611bee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.0
    - pip
  run:
    - python >=3.7
    - adcc >=0.15.4
    - respondo >=0.0.4
    - numpy <=1.23.5
    - sympy
    - tqdm
    - anytree

test:
  imports:
    - responsefun
  commands:
    - pip check
  requires:
    - pip
    - pytest
    - zarr

about:
  home: https://github.com/maxscheurer/responsefun
  summary: 'Fun with automatic evaluation of response functions in the ADC framework'
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apapapostolou
    - maxscheurer
